language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=4.18.20
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - TESTSUITE=1 LIBS=-ljemalloc

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"
    - arch: ppc64le
      compiler: gcc
      env: OPTS="--disable-ssl"
    - arch: ppc64le
      compiler: gcc
      env: TESTSUITE=1 OPTS="--enable-shared"
    - arch: ppc64le
      compiler: gcc
      env: TESTSUITE=1 LIBS=-ljemalloc

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
